//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#loom
////
//// DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the corresponding
//// .loom.html template file and run `./glimr loom:compile`.
////

import glimr/loom/runtime

pub fn render(name name: String, email email: String) -> String {
  ""
  <> "\n\n<div class=\"person\">\n  <p>"
  <> runtime.display(name)
  <> "</p>\n  <p>"
  <> runtime.display(email)
  <> "</p>\n</div>\n"
}

